/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;

import javax.swing.JOptionPane;

/**
 *
 * @author udity
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BOOK_TICKET = new javax.swing.JButton();
        LIST_TICKETS = new javax.swing.JButton();
        CHANGE_PASSWORD = new javax.swing.JButton();
        DELETE_MY_ACCOUNT = new javax.swing.JButton();
        LOG_OUT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUSTOMER");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER");

        BOOK_TICKET.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BOOK_TICKET.setText("BOOK TICKET");
        BOOK_TICKET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOK_TICKETActionPerformed(evt);
            }
        });

        LIST_TICKETS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LIST_TICKETS.setText("LIST TICKETS");
        LIST_TICKETS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIST_TICKETSActionPerformed(evt);
            }
        });

        CHANGE_PASSWORD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CHANGE_PASSWORD.setText("CHANGE PASSWORD");
        CHANGE_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGE_PASSWORDActionPerformed(evt);
            }
        });

        DELETE_MY_ACCOUNT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DELETE_MY_ACCOUNT.setText("DELETE MY ACCOUNT");
        DELETE_MY_ACCOUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE_MY_ACCOUNTActionPerformed(evt);
            }
        });

        LOG_OUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LOG_OUT.setText("LOG OUT");
        LOG_OUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOG_OUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BOOK_TICKET, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CHANGE_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(LIST_TICKETS, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DELETE_MY_ACCOUNT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(LOG_OUT)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BOOK_TICKET)
                    .addComponent(CHANGE_PASSWORD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LIST_TICKETS)
                    .addComponent(DELETE_MY_ACCOUNT))
                .addGap(26, 26, 26)
                .addComponent(LOG_OUT)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOOK_TICKETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOK_TICKETActionPerformed
        // TODO add your handling code here:
        new Book_Ticket().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BOOK_TICKETActionPerformed

    private void LIST_TICKETSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIST_TICKETSActionPerformed
        // TODO add your handling code here:
        new List_Tickets().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LIST_TICKETSActionPerformed

    private void DELETE_MY_ACCOUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE_MY_ACCOUNTActionPerformed
        // TODO add your handling code here:
        new Delete_Account().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_DELETE_MY_ACCOUNTActionPerformed

    private void LOG_OUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOG_OUTActionPerformed
        // TODO add your handling code here:
        int sure = JOptionPane.showConfirmDialog(null, "Are you sure?");
        
        if(sure == JOptionPane.NO_OPTION   ||   sure == JOptionPane.CANCEL_OPTION){
            return;
        }
        
        
        AirlineReservationSystem.user = null;
        AirlineReservationSystem.email = null;
        
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LOG_OUTActionPerformed

    private void CHANGE_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGE_PASSWORDActionPerformed
        // TODO add your handling code here:
        new Change_Password().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CHANGE_PASSWORDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOOK_TICKET;
    private javax.swing.JButton CHANGE_PASSWORD;
    private javax.swing.JButton DELETE_MY_ACCOUNT;
    private javax.swing.JButton LIST_TICKETS;
    private javax.swing.JButton LOG_OUT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
