/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author udity
 */
public class List_Employees extends javax.swing.JFrame {
    
    Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    int result = 0;
    
    /**
     * Creates new form List_Employees
     */
    public List_Employees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EMPLOYEE_TABLE = new javax.swing.JTable();
        SEARCH = new javax.swing.JTextField();
        ADD_EMPLOYEE = new javax.swing.JButton();
        REMOVE_EMPLOYEE = new javax.swing.JButton();
        GO_BACK_TO_PREVIOUS_MENU = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NEW_MOBILE_NUMBER = new javax.swing.JTextField();
        UPDATE_MOBILE_NUMBER = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIST EMPLOYEES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EMPLOYEES");

        EMPLOYEE_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(EMPLOYEE_TABLE);

        SEARCH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SEARCHKeyReleased(evt);
            }
        });

        ADD_EMPLOYEE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ADD_EMPLOYEE.setText("ADD EMPLOYEE");
        ADD_EMPLOYEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_EMPLOYEEActionPerformed(evt);
            }
        });

        REMOVE_EMPLOYEE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        REMOVE_EMPLOYEE.setText("REMOVE EMPLOYEE");
        REMOVE_EMPLOYEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVE_EMPLOYEEActionPerformed(evt);
            }
        });

        GO_BACK_TO_PREVIOUS_MENU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GO_BACK_TO_PREVIOUS_MENU.setText("GO BACK TO PREVIOUS MENU");
        GO_BACK_TO_PREVIOUS_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GO_BACK_TO_PREVIOUS_MENUActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("<-- SEARCH");

        UPDATE_MOBILE_NUMBER.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UPDATE_MOBILE_NUMBER.setText("UPDATE_MOBILE_NUMBER");
        UPDATE_MOBILE_NUMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE_MOBILE_NUMBERActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(2);
        jTextArea1.setText("NOTE: Search & select cannot not be used together for\nupdation of mobile number or removal of an employee.");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(GO_BACK_TO_PREVIOUS_MENU)
                                .addGap(101, 101, 101)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ADD_EMPLOYEE)
                                    .addComponent(jLabel2)
                                    .addComponent(REMOVE_EMPLOYEE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NEW_MOBILE_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UPDATE_MOBILE_NUMBER))
                            .addComponent(jScrollPane2))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UPDATE_MOBILE_NUMBER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NEW_MOBILE_NUMBER)
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18)
                        .addComponent(ADD_EMPLOYEE)
                        .addGap(18, 18, 18)
                        .addComponent(REMOVE_EMPLOYEE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(GO_BACK_TO_PREVIOUS_MENU))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GO_BACK_TO_PREVIOUS_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GO_BACK_TO_PREVIOUS_MENUActionPerformed
        // TODO add your handling code here:
        new Manager().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_GO_BACK_TO_PREVIOUS_MENUActionPerformed

    private void SEARCHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SEARCHKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) EMPLOYEE_TABLE.getModel();
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        EMPLOYEE_TABLE.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(SEARCH.getText()));
    }//GEN-LAST:event_SEARCHKeyReleased

    private void ADD_EMPLOYEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_EMPLOYEEActionPerformed
        // TODO add your handling code here:
        new Create_A_New_Account().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ADD_EMPLOYEEActionPerformed

    private void REMOVE_EMPLOYEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVE_EMPLOYEEActionPerformed
        // TODO add your handling code here:
        int sure = JOptionPane.showConfirmDialog(null, "Are you sure?");
        
        if(sure == JOptionPane.NO_OPTION   ||   sure == JOptionPane.CANCEL_OPTION){
            return;
        }
        
        
        conn = AirlineReservationSystem.connectDB();
        
        try{
            int row = EMPLOYEE_TABLE.getSelectedRow();
            
            String sql = "Delete from EMPLOYEE where EMAIL=?";
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, EMPLOYEE_TABLE.getModel().getValueAt(row, 6).toString());
            result = pst.executeUpdate();

            if(result != 0){
                JOptionPane.showMessageDialog(null, "Employee Removed Succesfully.");
                
                new List_Employees().setVisible(true);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "There was a problem removing the Employee.");
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_REMOVE_EMPLOYEEActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = AirlineReservationSystem.connectDB();
        
        try{
            String sql = "Select * from EMPLOYEE where MANAGER_EMAIL=? order by First_NAME, MIDDLE_NAME, LAST_NAME";
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, AirlineReservationSystem.email);
            rs = (OracleResultSet) pst.executeQuery();
            
            EMPLOYEE_TABLE.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void UPDATE_MOBILE_NUMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE_MOBILE_NUMBERActionPerformed
        // TODO add your handling code here:
        int sure = JOptionPane.showConfirmDialog(null, "Are you sure?");
        
        if(sure == JOptionPane.NO_OPTION   ||   sure == JOptionPane.CANCEL_OPTION){
            return;
        }
        
        conn = AirlineReservationSystem.connectDB();
        
        try{
            int row = EMPLOYEE_TABLE.getSelectedRow();
            
            String sql = "Update EMPLOYEE set MOBILE_NO=? where EMAIL=?";
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            
            
            if(NEW_MOBILE_NUMBER.getText().length() != 10){
                JOptionPane.showMessageDialog(null, "Invalid Mobile Number.");
                return;
            }
            else{
                pst.setString(1, NEW_MOBILE_NUMBER.getText());
            }
            
            pst.setString(2, EMPLOYEE_TABLE.getModel().getValueAt(row, 6).toString());
            
            
            result = pst.executeUpdate();

            if(result != 0){
                JOptionPane.showMessageDialog(null, "Mobile Number Updated Succesfully.");
                
                new List_Employees().setVisible(true);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "There was a problem updating your mobile number.");
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_UPDATE_MOBILE_NUMBERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_Employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_EMPLOYEE;
    private javax.swing.JTable EMPLOYEE_TABLE;
    private javax.swing.JButton GO_BACK_TO_PREVIOUS_MENU;
    private javax.swing.JTextField NEW_MOBILE_NUMBER;
    private javax.swing.JButton REMOVE_EMPLOYEE;
    private javax.swing.JTextField SEARCH;
    private javax.swing.JButton UPDATE_MOBILE_NUMBER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
