/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author udity
 */
public class List_Customers extends javax.swing.JFrame {
    
    Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    int result = 0;
    
    /**
     * Creates new form List_Customers
     */
    public List_Customers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CUSTOMER_TABLE = new javax.swing.JTable();
        SEARCH = new javax.swing.JTextField();
        UPDATE_MOBILE_NUMBER = new javax.swing.JButton();
        REMOVE_CUSTOMER = new javax.swing.JButton();
        NEW_MOBILE_NUMBER = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        GO_BACK_TO_PREVIOUS_MENU = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIST CUSTOMERS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CUSTOMERS");

        CUSTOMER_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(CUSTOMER_TABLE);

        SEARCH.setToolTipText("");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        SEARCH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SEARCHKeyReleased(evt);
            }
        });

        UPDATE_MOBILE_NUMBER.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UPDATE_MOBILE_NUMBER.setText("UPDATE MOBILE NUMBER");
        UPDATE_MOBILE_NUMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE_MOBILE_NUMBERActionPerformed(evt);
            }
        });

        REMOVE_CUSTOMER.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        REMOVE_CUSTOMER.setText("REMOVE CUSTOMER");
        REMOVE_CUSTOMER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVE_CUSTOMERActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("<-- SEARCH HERE");

        GO_BACK_TO_PREVIOUS_MENU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GO_BACK_TO_PREVIOUS_MENU.setText("GO BACK TO PREVIOUS MENU");
        GO_BACK_TO_PREVIOUS_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GO_BACK_TO_PREVIOUS_MENUActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(2);
        jTextArea1.setText("NOTE: Search & select cannot not be used together for\nupdation of mobile number or removal of a customer.");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GO_BACK_TO_PREVIOUS_MENU)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NEW_MOBILE_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(REMOVE_CUSTOMER)
                                            .addComponent(UPDATE_MOBILE_NUMBER, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UPDATE_MOBILE_NUMBER)
                            .addComponent(NEW_MOBILE_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(REMOVE_CUSTOMER)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(GO_BACK_TO_PREVIOUS_MENU)
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = AirlineReservationSystem.connectDB();
        
        try{
            String sql = "Select * from CUSTOMER order by First_NAME, MIDDLE_NAME, LAST_NAME";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
            
            CUSTOMER_TABLE.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void SEARCHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SEARCHKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) CUSTOMER_TABLE.getModel();
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        CUSTOMER_TABLE.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(SEARCH.getText()));
    }//GEN-LAST:event_SEARCHKeyReleased

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHActionPerformed

    private void UPDATE_MOBILE_NUMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE_MOBILE_NUMBERActionPerformed
        // TODO add your handling code here:
        int sure = JOptionPane.showConfirmDialog(null, "Are you sure?");
        
        if(sure == JOptionPane.NO_OPTION   ||   sure == JOptionPane.CANCEL_OPTION){
            return;
        }
        
        conn = AirlineReservationSystem.connectDB();
        
        try{
            int row = CUSTOMER_TABLE.getSelectedRow();
            
            String sql = "Update CUSTOMER set MOBILE_NO=? where EMAIL=?";
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            
            
            if(NEW_MOBILE_NUMBER.getText().length() != 10){
                JOptionPane.showMessageDialog(null, "Invalid Mobile Number.");
                return;
            }
            else{
                pst.setString(1, NEW_MOBILE_NUMBER.getText());
            }
            
            pst.setString(2, CUSTOMER_TABLE.getModel().getValueAt(row, 6).toString());
            
            
            result = pst.executeUpdate();

            if(result != 0){
                JOptionPane.showMessageDialog(null, "Mobile Number Updated Succesfully.");
                
                new List_Customers().setVisible(true);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "There was a problem updating your mobile number.");
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_UPDATE_MOBILE_NUMBERActionPerformed

    private void REMOVE_CUSTOMERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVE_CUSTOMERActionPerformed
        // TODO add your handling code here:
        int sure = JOptionPane.showConfirmDialog(null, "Are you sure?");
        
        if(sure == JOptionPane.NO_OPTION   ||   sure == JOptionPane.CANCEL_OPTION){
            return;
        }
        
        
        conn = AirlineReservationSystem.connectDB();
        
        try{
            int row = CUSTOMER_TABLE.getSelectedRow();
            
            String sql = "Delete from CUSTOMER where EMAIL=?";
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, CUSTOMER_TABLE.getModel().getValueAt(row, 6).toString());
            result = pst.executeUpdate();

            if(result != 0){
                JOptionPane.showMessageDialog(null, "Customer Removed Succesfully.");
                
                new List_Customers().setVisible(true);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "There was a problem removing the customer.");
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_REMOVE_CUSTOMERActionPerformed

    private void GO_BACK_TO_PREVIOUS_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GO_BACK_TO_PREVIOUS_MENUActionPerformed
        // TODO add your handling code here:
        if(AirlineReservationSystem.user == "MANAGER"){
            new Manager().setVisible(true);
        }
        else if(AirlineReservationSystem.user == "EMPLOYEE"){
            new Employee().setVisible(true);
        }
        
        setVisible(false);
    }//GEN-LAST:event_GO_BACK_TO_PREVIOUS_MENUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_Customers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CUSTOMER_TABLE;
    private javax.swing.JButton GO_BACK_TO_PREVIOUS_MENU;
    private javax.swing.JTextField NEW_MOBILE_NUMBER;
    private javax.swing.JButton REMOVE_CUSTOMER;
    private javax.swing.JTextField SEARCH;
    private javax.swing.JButton UPDATE_MOBILE_NUMBER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
