/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;

import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author udity
 */
public class Passengers extends javax.swing.JFrame {
    
    Connection conn = null;
    OraclePreparedStatement pst1 = null;
    OraclePreparedStatement pst2 = null;
    OracleResultSet rs = null;
    int result = 0;
    
    /**
     * Creates new form Passengers
     */
    public Passengers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FIRST_NAME = new javax.swing.JTextField();
        MIDDLE_NAME = new javax.swing.JTextField();
        LAST_NAME = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AGE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MOBILE_NUMBER = new javax.swing.JTextField();
        GENERATE_PRICE = new javax.swing.JButton();
        ADD_PASSENGER = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CURRENT_PASSENGERS_PRICE = new javax.swing.JTextField();
        TOTAL_PRICE = new javax.swing.JTextField();
        PROCEED_TO_PAYMENT = new javax.swing.JButton();
        MALE = new javax.swing.JRadioButton();
        FEMALE = new javax.swing.JRadioButton();
        OTHER = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        CANCEL_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PASSENGERS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADD PASSENGER DETAILS");

        jLabel2.setText("FUL NAME");

        jLabel3.setText("FIRST NAME");

        jLabel4.setText("MIDDLE NAME");

        jLabel5.setText("LAST NAME");

        jLabel6.setText("GENDER");

        jLabel7.setText("AGE");

        GENERATE_PRICE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GENERATE_PRICE.setText("GENERATE PRICE");
        GENERATE_PRICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENERATE_PRICEActionPerformed(evt);
            }
        });

        ADD_PASSENGER.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ADD_PASSENGER.setText("ADD PASSENGER");
        ADD_PASSENGER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_PASSENGERActionPerformed(evt);
            }
        });

        jLabel8.setText("MOBILE NUMBER");

        jLabel9.setText("CURRENT PASSENGER'S PRICE");

        CURRENT_PASSENGERS_PRICE.setEditable(false);

        TOTAL_PRICE.setEditable(false);

        PROCEED_TO_PAYMENT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PROCEED_TO_PAYMENT.setText("PROCEED TO PAYMENT");
        PROCEED_TO_PAYMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROCEED_TO_PAYMENTActionPerformed(evt);
            }
        });

        buttonGroup1.add(MALE);
        MALE.setText("Male");

        buttonGroup1.add(FEMALE);
        FEMALE.setText("Female");

        buttonGroup1.add(OTHER);
        OTHER.setText("Other");

        jLabel10.setText("TOTAL PRICE");

        CANCEL_BUTTON.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CANCEL_BUTTON.setText("CANCEL");
        CANCEL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCEL_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MALE)
                                        .addGap(4, 4, 4)
                                        .addComponent(FEMALE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(OTHER))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LAST_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(FIRST_NAME)
                                            .addComponent(MIDDLE_NAME)))
                                    .addComponent(AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MOBILE_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PROCEED_TO_PAYMENT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                        .addComponent(CANCEL_BUTTON))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TOTAL_PRICE)
                                            .addComponent(CURRENT_PASSENGERS_PRICE))))
                                .addGap(1, 1, 1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GENERATE_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ADD_PASSENGER, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FIRST_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MIDDLE_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAST_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(MALE)
                    .addComponent(FEMALE)
                    .addComponent(OTHER))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MOBILE_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADD_PASSENGER)
                    .addComponent(GENERATE_PRICE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CURRENT_PASSENGERS_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TOTAL_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PROCEED_TO_PAYMENT)
                    .addComponent(CANCEL_BUTTON))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int GeneratePrice(){
        conn = AirlineReservationSystem.connectDB();
        
        try{
            int currPrice = 0;
            
            String sql1 = "Select * from FLIGHT where FLIGHT_ID=?";
            
            pst1 = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst1.setString(1, Integer.toString(AirlineReservationSystem.flight_id));
            rs = (OracleResultSet) pst1.executeQuery();
            
            if(rs.next()){
                if(AirlineReservationSystem.CLASS == "Economy"){
                    currPrice = Integer.parseInt(rs.getString("ECONOMY_PRICE"));
                }
                else if(AirlineReservationSystem.CLASS == "Business"){
                    currPrice = Integer.parseInt(rs.getString("BUSINESS_PRICE"));
                }
                
                if(Integer.parseInt(AGE.getText()) < 12){
                    currPrice = currPrice * 75 / 100;
                }
                
                return currPrice;
            }
            else{
                JOptionPane.showMessageDialog(null, "There was a problem generating the prices.");
                
                return 0;
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        return 0;
    }
    
    
    private void GENERATE_PRICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENERATE_PRICEActionPerformed
        // TODO add your handling code here:
        int currPrice = GeneratePrice();
        
        CURRENT_PASSENGERS_PRICE.setText(Integer.toString(currPrice));
        TOTAL_PRICE.setText(Integer.toString(AirlineReservationSystem.total_price + currPrice));
    }//GEN-LAST:event_GENERATE_PRICEActionPerformed

    private void PROCEED_TO_PAYMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROCEED_TO_PAYMENTActionPerformed
        // TODO add your handling code here:
        if(AirlineReservationSystem.passenger_count == 0){
            JOptionPane.showMessageDialog(null,"No passengers have been added yet. Please add a passenger first.");
            return;
        }
        
        int sure = JOptionPane.showConfirmDialog(null, "Are you sure? [NOTE: We do not provide refunds on cacellation.]");
        
        if(sure == JOptionPane.NO_OPTION   ||   sure == JOptionPane.CANCEL_OPTION){
            return;
        }
        
        new Payment().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_PROCEED_TO_PAYMENTActionPerformed

    private void ADD_PASSENGERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_PASSENGERActionPerformed
        // TODO add your handling code here:
        if(AirlineReservationSystem.passenger_count >= 5){
            JOptionPane.showMessageDialog(null,"Maximum 5 Passengers can be added at a time.");
            return;
        }
        
        
        conn = AirlineReservationSystem.connectDB();
        
        try{
            int count = 0, ticket_id = 0, currPrice = (int) GeneratePrice();
            
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MMM-yyyy");
            
            String sql1 = "Select * from TICKET";
            
            pst1 = (OraclePreparedStatement) conn.prepareStatement(sql1);
            rs = (OracleResultSet) pst1.executeQuery();
            
            while(rs.next()){
                count++;
            }
            
            ticket_id = 100000 + (count + 1);
            
            
            String sql2 = "Insert into TICKET values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            pst2 = (OraclePreparedStatement) conn.prepareStatement(sql2);
            
            pst2.setString(1, Integer.toString(ticket_id));
            pst2.setString(2, Integer.toString(AirlineReservationSystem.flight_id));
            pst2.setString(3, formatter.format(AirlineReservationSystem.DOJ));
            pst2.setString(4, AirlineReservationSystem.CLASS);
            
            pst2.setString(5, AirlineReservationSystem.email);

            pst2.setString(6, FIRST_NAME.getText());
            pst2.setString(7, MIDDLE_NAME.getText());
            pst2.setString(8, LAST_NAME.getText());

            if(MALE.isSelected()){
                pst2.setString(9, "Male");
            }
            else if(FEMALE.isSelected()){
                pst2.setString(9, "Female");
            }
            else if(OTHER.isSelected()){
                pst2.setString(9, "Other");
            }

            pst2.setString(10, AGE.getText());
            
            if(MOBILE_NUMBER.getText().length() != 10){
                JOptionPane.showMessageDialog(null, "Invalid Mobile Number.");
                return;
            }
            else{
                pst2.setString(11, MOBILE_NUMBER.getText());
            }
            
            pst2.setString(12, Integer.toString(currPrice));
            
            pst2.setString(13, "Booked");
            
            result = pst2.executeUpdate();
            
            if(result != 0){
                JOptionPane.showMessageDialog(null,"Passeger Added Successfully.");
                AirlineReservationSystem.passenger_count++;
                
                
                FIRST_NAME.setText(null);
                MIDDLE_NAME.setText(null);
                LAST_NAME.setText(null);
                
                AGE.setText(null);
                MOBILE_NUMBER.setText(null);
                
                CURRENT_PASSENGERS_PRICE.setText(null);
                TOTAL_PRICE.setText(null);
                
            }
            else{
                JOptionPane.showMessageDialog(null,"There was a problem adding the passenger.");
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }                                              

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ADD_PASSENGERActionPerformed

    private void CANCEL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCEL_BUTTONActionPerformed
        // TODO add your handling code here:
        int sure = JOptionPane.showConfirmDialog(null, "Are you sure?");
        
        if(sure == JOptionPane.NO_OPTION   ||   sure == JOptionPane.CANCEL_OPTION){
            return;
        }
        
        JOptionPane.showMessageDialog(null,AirlineReservationSystem.passenger_count);
        
        conn = AirlineReservationSystem.connectDB();
        
        try{
            int count = 0, ticket_id = 0;
            
            String sql1 = "Select * from TICKET";
            
            pst1 = (OraclePreparedStatement) conn.prepareStatement(sql1);
            rs = (OracleResultSet) pst1.executeQuery();
            
            while(rs.next()){
                count++;
            }
            
            for(int i=0; i < AirlineReservationSystem.passenger_count; i++){
                ticket_id = (100000 + count) - i;
                
                String sql2 = "Delete from TICKET where TICKET_ID=?";
                
                pst2 = (OraclePreparedStatement) conn.prepareStatement(sql2);
                pst2.setString(1, Integer.toString(ticket_id));
                result = pst2.executeUpdate();
            }
            
            
            if(AirlineReservationSystem.user == "MANAGER"){
                new Manager().setVisible(true);
            }
            else if(AirlineReservationSystem.user == "EMPLOYEE"){
                new Employee().setVisible(true);
            }
            else if(AirlineReservationSystem.user == "CUSTOMER"){
                new Customer().setVisible(true);
            }
            
            setVisible(false);
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_CANCEL_BUTTONActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        AirlineReservationSystem.passenger_count = 0;
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passengers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_PASSENGER;
    private javax.swing.JTextField AGE;
    private javax.swing.JButton CANCEL_BUTTON;
    private javax.swing.JTextField CURRENT_PASSENGERS_PRICE;
    private javax.swing.JRadioButton FEMALE;
    private javax.swing.JTextField FIRST_NAME;
    private javax.swing.JButton GENERATE_PRICE;
    private javax.swing.JTextField LAST_NAME;
    private javax.swing.JRadioButton MALE;
    private javax.swing.JTextField MIDDLE_NAME;
    private javax.swing.JTextField MOBILE_NUMBER;
    private javax.swing.JRadioButton OTHER;
    private javax.swing.JButton PROCEED_TO_PAYMENT;
    private javax.swing.JTextField TOTAL_PRICE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
