/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;

import java.sql.Connection;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author udity
 */
public class Payment extends javax.swing.JFrame {
    
    Connection conn = null;
    OraclePreparedStatement pst1 = null, pst2 = null;
    OracleResultSet rs = null;
    int result = 0;
    
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BANK = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        USER_ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PASSWORD = new javax.swing.JPasswordField();
        PROCEED = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAYMENT");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PAYMENT GATEWAY");

        jLabel2.setText("BANK");

        BANK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AXIS BANK", "BANK OF INDIA", "HDFC BANK", "ICICI BANK", "STATE BANK OF INDIA" }));
        BANK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BANKActionPerformed(evt);
            }
        });

        jLabel3.setText("USER ID");

        jLabel4.setText("PASSWORD");

        PROCEED.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PROCEED.setText("PROCEED");
        PROCEED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROCEEDActionPerformed(evt);
            }
        });

        CANCEL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CANCEL.setText("CANCEL");
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PROCEED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CANCEL))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addComponent(BANK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PASSWORD)
                            .addComponent(USER_ID))))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BANK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(USER_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PROCEED)
                    .addComponent(CANCEL))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BANKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BANKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BANKActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        // TODO add your handling code here:
        int sure = JOptionPane.showConfirmDialog(null, "Are you sure?");
        
        if(sure == JOptionPane.NO_OPTION   ||   sure == JOptionPane.CANCEL_OPTION){
            return;
        }
        
        
        conn = AirlineReservationSystem.connectDB();
        
        try{
            int count = 0, ticket_id = 0;
            
            String sql1 = "Select * from TICKET";
            
            pst1 = (OraclePreparedStatement) conn.prepareStatement(sql1);
            rs = (OracleResultSet) pst1.executeQuery();
            
            while(rs.next()){
                count++;
            }
            
            for(int i=0; i < AirlineReservationSystem.passenger_count; i++){
                ticket_id = (100000 + count) - i;
                
                String sql2 = "Delete from TICKET where TICKET_ID=?";
                
                pst2 = (OraclePreparedStatement) conn.prepareStatement(sql2);
                pst2.setString(1, Integer.toString(ticket_id));
                result = pst2.executeUpdate();
            }
            
            
            if(AirlineReservationSystem.user == "MANAGER"){
                new Manager().setVisible(true);
            }
            else if(AirlineReservationSystem.user == "EMPLOYEE"){
                new Employee().setVisible(true);
            }
            else if(AirlineReservationSystem.user == "CUSTOMER"){
                new Customer().setVisible(true);
            }
            
            setVisible(false);
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_CANCELActionPerformed

    private void PROCEEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROCEEDActionPerformed
        // TODO add your handling code here:
        conn = AirlineReservationSystem.connectDB();
        
        try{
            String sql = "Select * from BANK_ACCOUNT where BANK_NAME=? and USER_ID=? and PASSWORD=?";
            
            pst1 = (OraclePreparedStatement) conn.prepareStatement(sql);
            
            pst1.setString(1, (String) BANK.getSelectedItem());
            pst1.setString(2, USER_ID.getText());
            pst1.setString(3, PASSWORD.getText());
            
            rs = (OracleResultSet) pst1.executeQuery();
            
            if(rs.next()){
                if(Integer.parseInt(rs.getString("BALANCE")) >= AirlineReservationSystem.total_price){
                    int updated_balance = Integer.parseInt(rs.getString("BALANCE")) - AirlineReservationSystem.total_price;
                    
                    String sql2 = "UPDATE BANK_ACCOUNT set BALANCE=? where USER_ID=?";
                    
                    pst2 = (OraclePreparedStatement) conn.prepareStatement(sql2);
                    pst2.setString(1, Integer.toString(updated_balance));
                    pst2.setString(2, USER_ID.getText());
                    
                    result = pst2.executeUpdate();
                    
                    if(result != 0){
                        JOptionPane.showMessageDialog(null, "Payment Completed Succesfully.");
                        JOptionPane.showMessageDialog(null, "Flight tickets for " + AirlineReservationSystem.passenger_count + " passenegers was booked successfully");
                        JOptionPane.showMessageDialog(null, "Please collect your tickets (with Seat Number) at the time of departure with an ID proof for verification.");
                        
                        if(AirlineReservationSystem.user == "MANAGER"){
                            new Manager().setVisible(true);
                        }
                        else if(AirlineReservationSystem.user == "EMPLOYEE"){
                            new Employee().setVisible(true);
                        }
                        else if(AirlineReservationSystem.user == "CUSTOMER"){
                            new Customer().setVisible(true);
                        }
                        
                        setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "There was a probem updating your account balance.");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Insufficient Account Balance");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Credentials");
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PROCEEDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BANK;
    private javax.swing.JButton CANCEL;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JButton PROCEED;
    private javax.swing.JTextField USER_ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
